<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "px_semantic_examples"
 *
 * Auto generated by Extension Builder 2014-01-20
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'PxSemantic Examples',
    'description' => 'Examples for usage of PxSemantic',
    'category' => 'fe',
    'author' => 'Andre Wuttig',
    'author_email' => 'wuttig@portrino.de',
    'author_company' => 'portrino GmbH',
    'state' => 'alpha',
    'uploadfolder' => '0',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.2.0-7.99.99',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];